sermons = [
    {
        "title": "The God Who Lifts Men Up",
        "description": "A sermon on divine elevation, breakthrough, open doors, overcoming delays, spiritual warfare, career advancement, business growth and destiny fulfilment.",
        "keywords": [
           "delayed breakthrough",
           "breaking stagnation",
           "career breakthrough",
           "career promotion",
           "business growth",
           "business breakthrough",
           "business expansion",
           "financial breakthrough",
           "divine favour in business",
           "favour at work",
           "promotion at work",
           "open doors",
           "closed doors",
           "destiny fulfilment",
           "destiny helpers",
           "spiritual warfare",
           "overcoming delays",
           "delayed blessings",
           "moving forward",
           "next level",
           "increase and expansion",
           "advancement in life",
           "divine elevation",
           "breaking limitations",
           "fruitfulness",
           "progress in life"
        ],
        "link": "https://t.me/apostleomo_messages/5"
    },
    {
        "title": "The Lifting of Men: God’s Criteria for Divine Promotion",
        "description": "In a world and nation rigged with casting down, God is still in the business of lifting His people. Apostle Omorogbe Aimiuwu powerfully teaches the divine criteria for supernatural lifting — beginning with the posture of your heart, followed by key virtues every believer must possess: humility, diligence, faithfulness, loyalty, obedience, righteousness, and genuine love for God.",
        "keywords": [
            "divine promotion",
            "supernatural promotion",
            "divine lifting",
            "destiny lifting",
            "kingdom advancement",
            "heart posture",
            "humility",
            "diligence",
            "faithfulness",
            "loyalty",
            "obedience",
            "righteousness",
            "pure heart",
            "purity of heart",
            "love for god",
            "kingdom virtues",
            "spiritual growth",
            "deeper walk with god",
            "encounter with god",
            "godly character",
            "character development",
            "spiritual maturity",
            "personal transformation",
            "godly leadership",
            "divine increase",
            "overcoming limitations",
            "casting down",
            "progress and increase",
            "walking with god",
            "living righteously"
        ],
        "link": "https://t.me/apostleomo_messages/4"
    },
    {
        "title": "The Prayer That Sustains You on Friday: When Faith is Tested",
        "description": "On this Good Friday, Apostle Omorogbe Aimiuwu brings a timely message from Luke 22. Jesus prayed for Peter that his faith would not fail even in his darkest Friday. God may not stop every battle, but He has prayed for your faith. You didn’t fail — you just didn’t finish.",
        "keywords": [
            "faith that does not fail",
            "i have prayed for you",
            "good friday",
            "easter retreat",
            "prayer for faith",
            "trials and tribulations",
            "going through friday",
            "tough times",
            "faith in trials",
            "jesus prayer for peter",
            "sustaining faith",
            "didn't fail just didn't finish",
            "spiritual endurance",
            "overcoming failure",
            "gods prayer for you",
            "easter message",
            "good friday message",
            "faith during storms",
            "conversion",
            "strength in weakness",
            "trusting god in difficulty",
            "apostle omorogbe aimiuwu",
            "easter 2026",
            "resilience in faith",
            "divine intercession",
            "standing strong",
            "perseverance",
            "victory after friday",
            "resurrection faith",
            "holy week"
        ],
        "link": "https://t.me/apostleomo_messages/7"
    },
    {
        "title": "God’s Power to Restore: Fight Yourself and Rise Again",
        "description": "On Day 2 of the Easter Retreat, Apostle Omorogbe Aimiuwu teaches from the story of Judas and the price of blood. No matter how deep your mistake or how dark your Saturday feels, God can turn your mess into a miracle. Fight yourself, confront your weaknesses, and get ready to rise again.",
        "keywords": [
            "easter retreat",
            "restoration",
            "god's redemption",
            "rise again",
            "fight yourself",
            "self discipline",
            "judas repentance",
            "price of blood",
            "overcoming failure",
            "turning mess into miracle",
            "saturday miracle",
            "resurrection power",
            "from dustbin to destiny",
            "breaking bad habits",
            "repentance and restoration",
            "you will rise again",
            "overcoming mistakes",
            "spiritual fighting",
            "personal transformation",
            "god turns failure around",
            "easter message",
            "apostle omorogbe aimiuwu",
            "easter 2026",
            "hope after failure",
            "self correction",
            "breaking limitations",
            "divine restoration",
            "new beginning",
            "resurrection life"
        ],
        "link": "https://t.me/apostleomo_messages/8"
    },
    {
        "title": "Altars: Commitment, Submission & The Sincerity of Heart",
        "description": "We have come to the place of altars — where destinies are shaped, spirits are encountered, and lives are transformed. Apostle Omorogbe Aimiuwu reveals the protocol for engaging altars: serious commitment, total submission to God’s will, and the sincerity and purity of the heart.",
        "keywords": [
            "altars",
            "spiritual altars",
            "altar of prayer",
            "commitment",
            "consistency",
            "submission to God",
            "sincerity of heart",
            "pure heart",
            "purity of heart",
            "consecration",
            "priesthood",
            "spiritual authority",
            "divine encounter",
            "encounter with God",
            "God's will",
            "total surrender",
            "consecrated living",
            "firstborn in Christ",
            "spiritual growth",
            "heart purity",
            "breaking casual Christianity",
            "dedication to God",
            "altar protocol",
            "spiritual sacrifice",
            "kingdom priesthood",
            "hearing God's voice",
            "deeper walk with God",
            "transformation",
            "holy living",
            "power of altars"
        ],
        "link": "https://t.me/apostleomo_messages/5"
    },
    {
        "title": "Altars and Commitments: The Ultimate Answer is the Holy Spirit",
        "description": "Altars are meeting points between the spirit realm and humanity. In this powerful teaching, Apostle Omorogbe Aimiuwu emphasizes that no altar responds without consistent commitment. The greatest answer you can receive on the altar is not money or material things — it is the Holy Spirit Himself.",
        "keywords": [
            "altars",
            "spiritual altars",
            "altar of prayer",
            "commitment",
            "consistent commitment",
            "steadfastness",
            "holy spirit",
            "power of the holy spirit",
            "encounter with the holy spirit",
            "sacrifice on the altar",
            "consistency in prayer",
            "prayer altar",
            "deeper walk with god",
            "hunger for god",
            "genuine encounters",
            "submission to god",
            "discerning the spirit",
            "spiritual signs",
            "believers gathering",
            "consecrated living",
            "altar protocol",
            "spiritual consistency",
            "holy spirit encounter",
            "power of commitment",
            "faithful on the altar",
            "spiritual sacrifice",
            "gods dealings",
            "transformation by the spirit",
            "prayer and commitment",
            "ultimate answer holy spirit"
        ],
        "link": "https://t.me/apostleomo_messages/6"
    }
]
