sermons = [
    {
        "title": "The God Who Lifts Men Up",
        "description": "A sermon on divine elevation, breakthrough, open doors, overcoming delays, spiritual warfare, career advancement, business growth and destiny fulfilment.",
        "keywords": [
            "lifting",
            "promotion",
            "breakthrough",
            "delay",
            "stagnation",
            "open doors",
            "career",
            "business",
            "favor",
            "favour"
        ],
        "link": "https://t.me/apostleomo_messages/5"
    },

    {
        "title": "The Lifting of Men: God’s Criteria for Divine Promotion",
        "keywords": [
            "lifting",
            "divine lifting",
            "divine promotion",
            "elevation",
            "supernatural promotion",
            "heart posture",
            "humility",
            "diligence",
            "faithfulness",
            "loyalty",
            "obedience",
            "righteousness",
            "pure heart",
            "love for God",
            "breaking stagnation",
            "casting down",
            "open doors",
            "breakthrough",
            "divine favour",
            "divine favor",
            "career advancement",
            "business success",
            "destiny lifting",
            "spiritual growth",
            "encounter with God",
            "kingdom virtues",
            "overcoming limitations",
            "divine advancement",
            "success in life",
            "progress and increase"
        ],
        "link": "https://t.me/apostleomo_messages/4"
    },

    {
        "title": "Altars: Commitment, Submission & The Sincerity of Heart",
        "keywords": [
            "altars",
            "spiritual altars",
            "altar of prayer",
            "commitment",
            "consistency",
            "submission to God",
            "sincerity of heart",
            "pure heart",
            "purity of heart",
            "consecration",
            "priesthood",
            "spiritual authority",
            "divine encounter",
            "encounter with God",
            "God's will",
            "total surrender",
            "consecrated living",
            "firstborn in Christ",
            "spiritual growth",
            "heart purity",
            "breaking casual Christianity",
            "dedication to God",
            "altar protocol",
            "spiritual sacrifice",
            "kingdom priesthood",
            "hearing God's voice",
            "deeper walk with God",
            "transformation",
            "holy living",
            "power of altars"
        ],
        "link": "https://t.me/apostleomo_messages/5"
    },

    {
        "title": "Altars and Commitments: The Ultimate Answer is the Holy Spirit",
        "keywords": [
            "altars",
            "spiritual altars",
            "altar of prayer",
            "commitment",
            "consistent commitment",
            "steadfastness",
            "holy spirit",
            "power of the holy spirit",
            "encounter with the holy spirit",
            "sacrifice on the altar",
            "consistency in prayer",
            "prayer altar",
            "deeper walk with god",
            "hunger for god",
            "genuine encounters",
            "submission to god",
            "discerning the spirit",
            "spiritual signs",
            "believers gathering",
            "consecrated living",
            "altar protocol",
            "spiritual consistency",
            "holy spirit encounter",
            "power of commitment",
            "faithful on the altar",
            "spiritual sacrifice",
            "gods dealings",
            "transformation by the spirit",
            "prayer and commitment",
            "ultimate answer holy spirit"
        ],
        "link": "https://t.me/apostleomo_messages/6"
    }
]